# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20170426_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
