# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20170426_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concernperson',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_person',
            field=models.BooleanField(default=False, verbose_name='is_person'),
        ),
        migrations.AddField(
            model_name='concernperson',
            name='division',
            field=models.CharField(max_length=40, null=True, verbose_name='division'),
        ),
        migrations.AddField(
            model_name='concernperson',
            name='order',
            field=models.IntegerField(max_length=2, null=True, verbose_name='order'),
        ),
    ]
