# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40, verbose_name='address'),
        ),
    ]
