# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20170427_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='division',
            field=models.CharField(default=1, max_length=40, verbose_name='division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
            preserve_default=False,
        ),
    ]
