# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_auto_20170427_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
