# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20170502_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernperson',
            name='status',
            field=models.BooleanField(verbose_name='status'),
        ),
    ]
