# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0008_auto_20170502_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernperson',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='concernperson',
            unique_together=set([]),
        ),
    ]
