# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0009_auto_20170502_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernperson',
            name='order',
            field=models.IntegerField(verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='concernperson',
            unique_together=set([('order', 'client')]),
        ),
    ]
