# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0010_auto_20170502_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='national_id',
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_persons', to='Clients.Client'),
        ),
    ]
