# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20170426_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
