# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Product')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Purpose')),
            ],
            options={
                'db_table': 'product_charges',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='charge',
            field=models.ManyToManyField(through='Portfolio.ProductCharge', to='Portfolio.Purpose'),
        ),
    ]
