# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20170423_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='start date'),
        ),
    ]
