# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20170426_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='start date'),
        ),
    ]
