# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20170427_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='purpose',
            name='start_date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='start date'),
        ),
    ]
