# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurpose',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
        ),
    ]
