# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170316_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/images', width_field='width_field'),
        ),
    ]
