# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20170426_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, null=True, verbose_name='employee id'),
        ),
    ]
