# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='employee id'),
        ),
    ]
