# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 05:04
from __future__ import unicode_literals

import Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_auto_20170427_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=Employees.models.upload_location, verbose_name='profile picture'),
        ),
    ]
