# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 11:43
from __future__ import unicode_literals

import Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(height_field='height_field', null=True, upload_to=Employees.models.upload_location, verbose_name='profile picture', width_field='width_field'),
        ),
    ]
