# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 03:46
from __future__ import unicode_literals

import Employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0006_auto_20170502_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=Employees.models.upload_location, verbose_name='profile picture'),
        ),
    ]
